# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  hardware = {
    openrazer ={
      enable = true;
      users = [ "astraeaf" ];
    };
    graphics = {
      enable = true;
      enable32Bit = true;
    };
    nvidia = {
      enable = true;
      package = config.boot.kernelPackages.nvidiaPackages.stable;
      modesetting.enable = true;
      open = true;
      nvidiaSettings = true;
    };
  };

  # services.xserver.videoDrivers = [ "nvidia" ];
  environment.systemPackages = with pkgs; [
    nvtopPackages.nvidia
  ];

  #nixpkgs.config = {
  #  cudaSupport = true;
  #  cudaCapability = [ "6.1" ];
  #};

  # needed for Windows to not freak out
  time.hardwareClockInLocalTime = true;

  # Bootloader.
  boot.loader.systemd-boot = {
    enable = true;
    windows = {
      "windows" =
        let
          boot-drive = "HD0b";
        in
        {
          title = "Windows";
          efiDeviceHandle = boot-drive;
          sortKey = "a_windows";
        };
    };

    edk2-uefi-shell.enable = true;
    edk2-uefi-shell.sortKey = "z_edk2";
  };
  boot.loader.efi.canTouchEfiVariables = true;

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "ahci"
    "usbhid"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];

  boot.kernelPackages = pkgs.linuxPackages_latest;

  boot.kernelModules = [ "kvm-amd" ];

  boot.extraModulePackages = with config.boot.kernelPackages; [
    openrazer
  ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/5ef6220e-9dc4-4fa1-a0e2-209ef0f134c5";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/A050-0CED";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/ebda0953-a1cd-4237-94f6-24e6f51893c2"; }
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp8s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
